on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --bare https://gitlab.com/open-ptv/purpletv.git .
          git remote set-url --push origin https://aeongdesu:${{ secrets.GH_TOKEN }}@github.com/nyanarchive/purpletv.git
          git push --mirror 
