on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --bare https://gitlab.com/open-ptv/purpletv .
          GITHUB_TOKEN=$GH_TOKEN git push --mirror https://github.com/nyanarchive/purpletv.git
