name: "gofile dl test"

on:
  workflow_dispatch:
    inputs:
      just_dl_status:
        type: boolean

jobs:
  dltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: npm install node-fetch@v2 --save
      - uses: actions/github-script@v6
        id: file
        env:
          IS_TRUE: ${{ github.event.inputs.just_dl_status }}
        with:
          result-encoding: string
          script: |
            const fetch = require("node-fetch")
            const fs = require("fs")
            const token = (await fetch("https://api.gofile.io/createAccount").then(res => res.json())).data.token
            const files = (await fetch(`https://api.gofile.io/getContent?contentId=oQ2OJ9&token=${token}&websiteToken=12345&cache=true`).then(res => res.json())).data.contents
            console.log(files)
            const file = files[Object.keys(files)[0]]
            if (process.env.IS_TRUE == 'false') await fetch(file.link, { headers: { "Cookie": `accountToken=${token}`} }).then(res => res.body.pipe(fs.createWriteStream(file.name)))
            else await fetch(file.link, { headers: { "Cookie": `accountToken=${token}`} }).then(res => res.ok)
            
            return file.name
      - name: upload file to artifact
        if: ${{ github.event.inputs.just_dl_status == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.file.outputs.result }}
          path: ${{ steps.file.outputs.result }}
