name: "gofile dl test"

on: workflow_dispatch

jobs:
  dltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: npm install node-fetch@v2 wget-improved --save
      - uses: actions/github-script@v6
        with:
          script: |
            const fetch = require("node-fetch")
            const wget = require("wget-improved")
            const token = await (await fetch("https://api.gofile.io/createAccount").then(res => res.json())).data.token
            const files = await (await fetch(`https://api.gofile.io/getContent?contentId=e1d0c303-10ef-4814-87e4-d89b2567fa21&token=${token}`).then(res => res.json())).data.contents
            const file = files.data.contents[Object.keys(files)[0]]
            const download = wget.download(file.link, file.name, { headers: { "token": token } })
          
            download.on("error", function(err) {
              console.log(err)
            })
            download.on("start", function(fileSize) {
              console.log(fileSize)
            })
            download.on("end", function(output) {
              console.log(output)
            })
