on: workflow_dispatch
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install aria2 axel -y
          end=$((SECONDS+18000))
          while [ $SECONDS -lt $end ]
          do
            aria2c --file-allocation=none "https://files.aeong.win/X23-81951_26100.1742.240906-0331.ge_release_svc_refresh_CLIENT_ENTERPRISES_OEM_x64FRE_en-us.iso"
            rm *.iso
            # axel "https://files.aeong.win/X23-81951_26100.1742.240906-0331.ge_release_svc_refresh_CLIENT_ENTERPRISES_OEM_x64FRE_en-us.iso"
            sleep 1
          done
