name: web3 upload bruh

on:
  workflow_dispatch:

jobs:
  web3:
    runs-on: ubuntu-latest
    env:
      LINK: "https://blameseouless.com/mappack"
    steps:
      - run: mkdir ghactions && wget -O ghactions/shigepack-20220408.zip ${{ env.LINK }}
      - uses: web3-storage/add-to-web3@v1
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: 'ghactions'

      - run: echo https://${{ steps.web3.outputs.cid }}.ipfs.infura-ipfs.io
