name: build obs-studio-browser
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: install required 
        run: pacman -Sy --noconfirm devtools btrfs-progs dbus sudo
      - name: make user for build
        run: |
          useradd -m user
          usermod -aG sudo user
          echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          sed -i "s|MAKEFLAGS=.*|MAKEFLAGS=-j$(nproc)|" /etc/makepkg.conf
      - name: build
        run: |
          git clone https://aur.archlinux.org/obs-studio-browser.git
          chown -R user: obs-studio-browser
          cd obs-studio-browser
          sudo -u user makepkg -sc
