name: build obs-studio-browser
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: install required 
        run: pacman -Sy --noconfirm devtools sudo
      - name: make user for build
        run: |
          useradd -m user
          echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          sed -i "s|MAKEFLAGS=.*|MAKEFLAGS=-j$(nproc)|" /etc/makepkg.conf
      - name: build
        run: |
          cd /home/user
          sudo -u user pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si
          sudo -u user yay -S --noconfirm obs-studio-browser 
          # sudo -u user git clone https://aur.archlinux.org/obs-studio-browser.git && cd obs-studio-browser && makepkg -sc --noconfirm


