name: build obs-studio-browser
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: install required 
        run: pacman -Sy --noconfirm devtools sudo
      - name: make user for build
        run: useradd -m user || true
      - name: build
        run: |
          git clone https://aur.archlinux.org/obs-studio-browser.git
          cd obs-studio-browser
          extra-x86_64-build -- -U user
