name: "osu!acc-rework"
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: clone osu
        run: git clone --recursive https://github.com/02Naitsirk/osu -b statistical_acc_pp
      - name: clone osu-tools-gui
        uses: actions/checkout@v3
        with:
          repository: "stanriders/osu-tools"
          ref: "perfcalc-gui"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: use local osu
        run: powershell .\UseLocalOsu.ps1
      - name: build
        run: dotnet build PerformanceCalculatorGUI/PerformanceCalculatorGUI.csproj -c Release -o build/
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-accrework
          path: build/
