name: ptv build test
on: 
  workflow_dispatch:
    inputs:
      apkm:
        required: true

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./toolchain
      PYTHONIOENCODING: utf-8

    steps:
      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
    
      - name: Checkout repo
        run: |
          git clone ([System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String("aHR0cHM6Ly9naXRsYWIuY29tL29wZW4tcHR2L3B1cnBsZXR2LmdpdC8="))) . -b FIXIES
          git config --system core.longpaths true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Prepare Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3

      - name: Prepare TTV apkm
        run: Invoke-WebRequest "${{ github.event.inputs.apkm }}" -OutFile ttv.apkm

      - name: Download APKEditor
        run: gh release download --repo REAndroid/APKEditor --pattern APKEditor-*.jar --output apkeditor.jar
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download dex2jar
        run: |
          gh release download --repo ThexXTURBOXx/dex2jar --pattern dex-tools-*.zip --output dex-tools.zip
          tar -xf dex-tools.zip
          rm dex-tools.zip
          mv dex-tools-*/ dex-tools
        env:
          GH_TOKEN: ${{ github.token }}

          
      - name: apkm -> apk
        run: |
          mkdir toolchain/apk
          java -jar apkeditor.jar m -i ./ttv.apkm -o toolchain/apk/ttv.apk

      - name: Setup virtualenv
        run: |
          uv venv
          .venv\Scripts\activate
          uv pip install pyaxmlparser
        working-directory: ${{ env.working-directory }}

      - name: dex2jar
        run: |
          cd dex-tools
          .\d2j-dex2jar ../toolchain/apk/ttv.apk -o ../Twitch/libs/tv.twitch.android.app.jar -f
     
      - name: Decompile
        run: |
          .venv\Scripts\activate
          python app.py --decompile
        working-directory: ${{ env.working-directory }}

      - name: Apply
        run: |
          .venv\Scripts\activate
          python app.py --apply
        working-directory: ${{ env.working-directory }}

      - name: Recompile
        run: |
          .venv\Scripts\activate
          python app.py --recompile
        working-directory: ${{ env.working-directory }}
        continue-on-error: true # because of signing

      - name: Signing
        run: |
          mkdir ${{ github.workspace }}/final
          java -jar bin/uber-apk-signer-1.3.0.jar --apks out/ --out ${{ github.workspace }}/final/
        working-directory: ${{ env.working-directory }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ptv
          path: ${{ github.workspace }}/final/*-debugSigned.apk
