name: Build Unbound
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download LSPatch
        run: gh release download --repo JingMatrix/LSPatch --pattern lspatch.jar
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download Discord
        run: |
          mkdir discord
          VERSION=$(curl -s https://tracker.vendetta.rocks/tracker/index | jq -r '.latest.stable')
          wget -O discord/base.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/base
          wget -O discord/config.arm64_v8a.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.arm64_v8a
          wget -O discord/config.armeabi_v7a.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.armeabi_v7a
          wget -O discord/config.x86_64.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.x86_64
          wget -O discord/config.x86.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.x86
          wget -O discord/config.hdpi.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.hdpi
          wget -O discord/config.xxhdpi.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.xxhdpi
          wget -O discord/config.en.apk -q https://tracker.vendetta.rocks/tracker/download/$VERSION/config.en

      - name: Download Unbound
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: main
          name: app-release
          repo: unbound-app/loader-android
          if_no_artifact_found: fail

      - name: Patch APK
        run: |
          mv app-release.apk unbound-loader.apk
          java -jar lspatch.jar -m unbound-loader.apk -l 2 -o lspatched/ discord/*.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: unbound
          path: ./lspatched/*
