name: "unstable"
on:
  workflow_dispatch:
    inputs:
      unstable:
        description: you know what it is
        type: string
        required: true
      replay:
        type: string
        required: true

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: levibostian/action-hide-sensitive-inputs@v1
      - name: download unstable
        run: |
          # since github changed default windows shell to powershell so yeah
          iwr "${{ inputs.unstable }}" -OutFile "unstable.7z"
          iwr "${{ inputs.replay }}" -OutFile "replay.osr"
          iwr "https://dl.nerinyan.moe/v2/d/2440836" -OutFile "song.zip"
          7z x unstable.7z -o"unstable"
          7z x song.zip -o"unstable/Songs/temp"
          ls
          ".\unstable/osu!.exe" -render "./replay.osr"
