on:
  workflow_dispatch:

jobs:
  main:
    name: "VRCDepots"
    runs-on: ubuntu-latest
    steps:
      - name: Setup steamcmd
        uses: andriivitiv/setup-steamcmd@v1
      - name: Download VRChat
        run: |
          steamcmd +login ${{ secrets.VRCDEPOTS_USER }} ${{ secrets.VRCDEPOTS_PASSWORD }} \
            +@sSteamCmdForcePlatformType windows \
            +force_install_dir ./vrchat_build \
            +app_update 438100 validate +quit
      - name: Check files
        run: |
          ls -la vrchat_build/
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: vrchat-public
          path: vrchat_build/
