name: windows-rdp

on: workflow_dispatch

jobs:
  windows-rdp:
    runs-on: windows-2025
    continue-on-error: true

    steps:
    # - name: Install winget
    #   run: winget upgrade winget --accept-package-agreements --accept-source-agreements --disable-interactivity

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.PASSWORD }}" -Force)
    
    - name: Install packages
      run: |
          winget install --id=Cloudflare.cloudflared -e --force --accept-source-agreements --disable-interactivity --silent --accept-package-agreement
          winget install --id=c0re100.qBittorrent-Enhanced-Edition -e --force --accept-source-agreements --disable-interactivity --silent --accept-package-agreement
          
    - name: Create Tunnel
      run: cloudflared --url rdp://localhost:3389 --logfile C:\cloudflared.log
      
    - name: show result link
      run: Start-Sleep -s 5 ; findstr "trycloudflare.com" C:\cloudflared.log

    - run: Start-Sleep -s 21600
